import React, { useState, useEffect } from 'react';
import { api } from '../../lib/api';
import {
  Play,
  CheckCircle2,
  AlertCircle,
  Database,
  RefreshCw,
  Sparkles,
  Copy,
  Check,
} from 'lucide-react';
import {
  ContentTypeDto,
  TemplateType,
  RenderOutputData,
} from '@cms/shared-types';

interface TemplatePreviewPaneProps {
  orgId: string;
  templateId?: string;
  templateType?: TemplateType;
  fieldsDraft?: Record<string, string>;
  bodyDraft: string;
  subjectDraft?: string;
  selectedSchema?: ContentTypeDto | null;
}

export const TemplatePreviewPane: React.FC<TemplatePreviewPaneProps> = ({
  orgId,
  templateId,
  fieldsDraft,
  bodyDraft,
  subjectDraft,
  selectedSchema,
}) => {
  const [outputTab, setOutputTab] = useState<'visual' | 'json'>('visual');
  const [variablesJson, setVariablesJson] = useState<string>('{}');
  const [previewOutput, setPreviewOutput] = useState<RenderOutputData | null>(null);
  const [previewError, setPreviewError] = useState<string | null>(null);
  const [isRendering, setIsRendering] = useState<boolean>(false);
  const [copiedJson, setCopiedJson] = useState<boolean>(false);

  // Automatically extracts {{variable}} placeholders from the template fields and creates sample test payload
  const generateSampleData = () => {
    const foundVars = new Set<string>();
    const regex = /\{\{([a-zA-Z0-9_]+)\}\}/g;

    // Scan all field formulas in fieldsDraft
    if (fieldsDraft) {
      Object.values(fieldsDraft).forEach((tpl) => {
        if (!tpl) return;
        let match;
        while ((match = regex.exec(tpl)) !== null) {
          const varName = match[1];
          if (
            varName &&
            !['if', 'else', 'each', 'unless', 'with', 'formatDate', 'uppercase', 'json'].includes(varName)
          ) {
            foundVars.add(varName);
          }
        }
      });
    }

    // Scan body and subject drafts
    [bodyDraft, subjectDraft].forEach((tpl) => {
      if (!tpl) return;
      let match;
      while ((match = regex.exec(tpl)) !== null) {
        const varName = match[1];
        if (
          varName &&
          !['if', 'else', 'each', 'unless', 'with', 'formatDate', 'uppercase', 'json'].includes(varName)
        ) {
          foundVars.add(varName);
        }
      }
    });

    const sample: Record<string, any> = {};

    if (foundVars.size > 0) {
      foundVars.forEach((v) => {
        const low = v.toLowerCase();
        if (low.includes('name') || low.includes('user') || low.includes('author') || low.includes('customer')) {
          sample[v] = 'Alex Doe';
        } else if (low.includes('title') || low.includes('heading')) {
          sample[v] = 'Sample Document Heading';
        } else if (low.includes('email')) {
          sample[v] = 'alex@example.com';
        } else if (low.includes('order') || low.includes('id')) {
          sample[v] = 'DOC-1024';
        } else if (low.includes('amount') || low.includes('total') || low.includes('price')) {
          sample[v] = 250;
        } else if (low.includes('url') || low.includes('link')) {
          sample[v] = 'https://example.com/demo';
        } else if (low.includes('date')) {
          sample[v] = new Date().toISOString().split('T')[0];
        } else if (low.includes('content') || low.includes('desc') || low.includes('body')) {
          sample[v] = 'This is dynamically rendered content generated by the template engine.';
        } else {
          sample[v] = `Sample ${v}`;
        }
      });
    } else {
      sample.title = 'Sample Document';
      sample.content = 'Welcome to the template rendering engine!';
    }

    setVariablesJson(JSON.stringify(sample, null, 2));
  };

  // Perform preview render
  const runPreview = async () => {
    setIsRendering(true);
    setPreviewError(null);

    try {
      let parsedVariables = {};
      if (variablesJson.trim()) {
        try {
          parsedVariables = JSON.parse(variablesJson);
        } catch (e: any) {
          throw new Error(`Invalid Variables JSON: ${e.message}`);
        }
      }

      const endpoint = templateId
        ? `/orgs/${orgId}/templates/${templateId}/preview`
        : `/orgs/${orgId}/templates/preview-raw`;

      const payload = {
        fieldsDraft,
        body: bodyDraft,
        subject: subjectDraft,
        variables: parsedVariables,
        contentTypeId: selectedSchema?.id,
      };

      const res = await api.post(endpoint, payload);
      setPreviewOutput(res.data.data || res.data);
    } catch (err: any) {
      const msg =
        err.response?.data?.error?.message ||
        err.response?.data?.message ||
        err.message ||
        'Preview generation failed';
      setPreviewError(msg);
    } finally {
      setIsRendering(false);
    }
  };

  // Initialize sample test data on mount or when schema changes
  useEffect(() => {
    generateSampleData();
  }, [selectedSchema]);

  const outputData: Record<string, any> =
    (previewOutput as any)?.data ||
    (previewOutput as any)?.output ||
    (previewOutput as any)?.payload ||
    (previewOutput ? (previewOutput as any) : {});

  const handleCopyJson = () => {
    navigator.clipboard.writeText(JSON.stringify(outputData, null, 2));
    setCopiedJson(true);
    setTimeout(() => setCopiedJson(false), 2000);
  };

  if (!selectedSchema) {
    return (
      <div className="flex flex-col items-center justify-center h-full min-h-[420px] text-center p-8 bg-white dark:bg-slate-900 rounded-2xl border border-dashed border-slate-200 dark:border-slate-800 shadow-sm">
        <div className="h-12 w-12 rounded-2xl bg-indigo-50 dark:bg-indigo-950/40 text-indigo-600 dark:text-indigo-400 flex items-center justify-center mb-3">
          <Database className="h-6 w-6" />
        </div>
        <h4 className="text-sm font-bold text-slate-800 dark:text-slate-200">
          Please select one model to continue
        </h4>
        <p className="text-xs text-slate-400 mt-1 max-w-xs leading-relaxed">
          Select an Output Model to configure dynamic input payloads and view the live rendered preview.
        </p>
      </div>
    );
  }

  const fieldEntries = Object.entries(outputData);

  return (
    <div className="flex flex-col space-y-4 pb-10">
      {/* Dynamic Input Variables Card */}
      <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-4 space-y-3 shadow-sm">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Database className="h-4 w-4 text-indigo-600 dark:text-indigo-400" />
            <div>
              <span className="text-xs font-bold text-slate-800 dark:text-slate-200">
                Dynamic Request Input (JSON)
              </span>
              <p className="text-[10px] text-slate-400">
                Schema-free input payload passed at runtime to populate template fields
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={generateSampleData}
              className="flex items-center gap-1 text-[11px] font-medium text-indigo-600 dark:text-indigo-400 hover:underline"
              title="Extract template variables from formulas"
            >
              <Sparkles className="h-3.5 w-3.5" />
              <span>Autofill Variables</span>
            </button>

            <button
              type="button"
              onClick={runPreview}
              disabled={isRendering}
              className="flex items-center gap-1.5 rounded-lg bg-indigo-600 px-3.5 py-1.5 text-xs font-semibold text-white shadow-sm hover:bg-indigo-700 disabled:opacity-50 transition"
            >
              {isRendering ? (
                <RefreshCw className="h-3.5 w-3.5 animate-spin" />
              ) : (
                <Play className="h-3.5 w-3.5 fill-white" />
              )}
              <span>{isRendering ? 'Rendering...' : 'Render Preview'}</span>
            </button>
          </div>
        </div>

        <div>
          <textarea
            rows={4}
            value={variablesJson}
            onChange={(e) => setVariablesJson(e.target.value)}
            className="w-full rounded-lg border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 p-2.5 font-mono text-xs text-slate-800 dark:text-slate-200 focus:outline-none focus:ring-1 focus:ring-indigo-500"
            placeholder='{ "title": "My Title", "content": "My Content" }'
          />
        </div>
      </div>

      {/* Error display */}
      {previewError && (
        <div className="rounded-xl border border-red-200 dark:border-red-900/50 bg-red-50 dark:bg-red-950/30 p-3 text-xs text-red-700 dark:text-red-300 flex items-start gap-2">
          <AlertCircle className="h-4 w-4 shrink-0 text-red-500 mt-0.5" />
          <div>
            <p className="font-semibold">Preview Render Failed</p>
            <p className="mt-0.5 font-mono text-[11px]">{previewError}</p>
          </div>
        </div>
      )}

      {/* Rendered Output Frame */}
      <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 overflow-hidden shadow-sm">
        {/* Output Header */}
        <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-800 bg-slate-50/70 dark:bg-slate-950/40 px-4 py-2.5">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="h-4 w-4 text-emerald-500" />
            <span className="text-xs font-semibold text-slate-800 dark:text-slate-200">
              Model Output: {selectedSchema ? selectedSchema.name : 'Template Output'}
            </span>
            <span className="text-[10px] font-mono text-slate-400 bg-slate-100 dark:bg-slate-800 px-2 py-0.5 rounded">
              {fieldEntries.length > 0 ? `${fieldEntries.length} ${fieldEntries.length === 1 ? 'field' : 'fields'}` : 'Ready'}
            </span>
          </div>

          {previewOutput && (
            <div className="flex items-center rounded-lg border border-slate-200 dark:border-slate-800 bg-slate-100 dark:bg-slate-800 p-0.5 text-[11px]">
              <button
                type="button"
                onClick={() => setOutputTab('visual')}
                className={`px-2.5 py-1 rounded-md font-semibold transition ${
                  outputTab === 'visual'
                    ? 'bg-white dark:bg-slate-700 text-indigo-600 dark:text-indigo-400 shadow-sm'
                    : 'text-slate-500 hover:text-slate-900'
                }`}
              >
                Visual Render
              </button>
              <button
                type="button"
                onClick={() => setOutputTab('json')}
                className={`px-2.5 py-1 rounded-md font-semibold transition ${
                  outputTab === 'json'
                    ? 'bg-white dark:bg-slate-700 text-indigo-600 dark:text-indigo-400 shadow-sm'
                    : 'text-slate-500 hover:text-slate-900'
                }`}
              >
                JSON Output
              </button>
            </div>
          )}
        </div>

        {/* Output Content Area */}
        <div className="p-4">
          {previewOutput ? (
            <div className="space-y-4">
              {/* Tab 1: Output JSON */}
              {outputTab === 'json' && (
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-[11px] font-mono text-slate-400">
                      Compiled Model Payload:
                    </span>
                    <div className="flex items-center gap-2">
                      <span className="text-[10px] text-emerald-600 dark:text-emerald-400 font-mono font-bold bg-emerald-50 dark:bg-emerald-950/50 px-2 py-0.5 rounded border border-emerald-200 dark:border-emerald-800">
                        200 OK
                      </span>
                      <button
                        type="button"
                        onClick={handleCopyJson}
                        className="inline-flex items-center gap-1 text-[11px] text-slate-500 hover:text-indigo-600 transition"
                      >
                        {copiedJson ? <Check className="h-3 w-3 text-emerald-500" /> : <Copy className="h-3 w-3" />}
                        <span>{copiedJson ? 'Copied' : 'Copy JSON'}</span>
                      </button>
                    </div>
                  </div>
                  <pre className="rounded-lg bg-slate-950 p-4 font-mono text-xs text-emerald-400 overflow-x-auto leading-relaxed border border-slate-800">
                    {JSON.stringify(outputData, null, 2)}
                  </pre>
                </div>
              )}

              {/* Tab 2: Visual Render Tab */}
              {outputTab === 'visual' && (() => {
                if (fieldEntries.length === 0) {
                  return (
                    <div className="p-8 text-center text-xs text-slate-400">
                      No rendered output returned.
                    </div>
                  );
                }

                // If Model has exactly 1 field
                if (fieldEntries.length === 1) {
                  const [fieldName, val] = fieldEntries[0];
                  const strVal = typeof val === 'string' ? val : JSON.stringify(val, null, 2);
                  const isHtml =
                    typeof val === 'string' &&
                    ((strVal.includes('<') && strVal.includes('>')) ||
                      fieldName.toLowerCase().includes('html') ||
                      fieldName.toLowerCase().includes('body') ||
                      fieldName.toLowerCase().includes('content'));

                  return (
                    <div className="space-y-3">
                      <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-950 overflow-hidden shadow-sm">
                        <div className="bg-slate-100/80 dark:bg-slate-900/80 px-4 py-2 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <div className="flex items-center gap-1.5">
                              <span className="h-2 w-2 rounded-full bg-slate-300 dark:bg-slate-700 inline-block" />
                              <span className="h-2 w-2 rounded-full bg-slate-300 dark:bg-slate-700 inline-block" />
                              <span className="h-2 w-2 rounded-full bg-slate-300 dark:bg-slate-700 inline-block" />
                            </div>
                            <span className="text-xs font-mono text-slate-600 dark:text-slate-300 ml-1">
                              Output: <strong className="text-indigo-600 dark:text-indigo-400">{fieldName}</strong>
                            </span>
                          </div>
                          <span className="text-[10px] bg-emerald-50 dark:bg-emerald-950/40 text-emerald-600 dark:text-emerald-400 px-2 py-0.5 rounded font-mono font-semibold border border-emerald-200/50 dark:border-emerald-800/40">
                            {isHtml ? 'Compiled HTML' : 'Text Output'}
                          </span>
                        </div>
                        <div className="p-6 bg-white dark:bg-slate-950 min-h-[280px]">
                          {isHtml ? (
                            <div
                              className="text-slate-900 dark:text-slate-100 text-sm leading-relaxed"
                              dangerouslySetInnerHTML={{ __html: strVal }}
                            />
                          ) : (
                            <p className="font-mono text-xs text-slate-800 dark:text-slate-200 whitespace-pre-wrap leading-relaxed">
                              {strVal}
                            </p>
                          )}
                        </div>
                      </div>
                    </div>
                  );
                }

                // If Model has multiple fields
                const htmlFields = fieldEntries.filter(
                  ([k, v]) =>
                    typeof v === 'string' &&
                    ((v.includes('<') && v.includes('>')) ||
                      k.toLowerCase().includes('html') ||
                      k.toLowerCase().includes('body') ||
                      k.toLowerCase().includes('content'))
                );
                const textFields = fieldEntries.filter(
                  ([k, v]) =>
                    !(
                      typeof v === 'string' &&
                      ((v.includes('<') && v.includes('>')) ||
                        k.toLowerCase().includes('html') ||
                        k.toLowerCase().includes('body') ||
                        k.toLowerCase().includes('content'))
                    )
                );

                return (
                  <div className="space-y-4">
                    {/* Rendered Text/Metadata Fields with strictly aligned 2-column grid */}
                    {textFields.length > 0 && (
                      <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-900/40 p-4 space-y-3">
                        <div className="flex items-center justify-between">
                          <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                            Output Fields ({textFields.length})
                          </span>
                          <span className="text-[10px] text-slate-400 font-mono">key-value output</span>
                        </div>
                        <div className="rounded-lg border border-slate-200/80 dark:border-slate-800 bg-white dark:bg-slate-900 overflow-hidden divide-y divide-slate-100 dark:divide-slate-800">
                          {textFields.map(([k, v]) => (
                            <div key={k} className="grid grid-cols-[130px_1fr] items-center px-4 py-2.5 text-xs">
                              <span className="font-mono font-semibold text-indigo-600 dark:text-indigo-400 truncate pr-2">
                                {k}:
                              </span>
                              <span className="font-medium text-slate-800 dark:text-slate-100 break-words">
                                {typeof v === 'object' ? JSON.stringify(v) : String(v)}
                              </span>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Rendered HTML Visual Canvases */}
                    {htmlFields.map(([k, v]) => (
                      <div
                        key={k}
                        className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-950 overflow-hidden shadow-sm"
                      >
                        <div className="bg-slate-100/80 dark:bg-slate-900/80 px-4 py-2.5 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <div className="flex items-center gap-1.5">
                              <span className="h-2 w-2 rounded-full bg-slate-300 dark:bg-slate-700 inline-block" />
                              <span className="h-2 w-2 rounded-full bg-slate-300 dark:bg-slate-700 inline-block" />
                              <span className="h-2 w-2 rounded-full bg-slate-300 dark:bg-slate-700 inline-block" />
                            </div>
                            <span className="text-xs font-mono text-slate-600 dark:text-slate-300 ml-1">
                              HTML Document: <strong className="text-indigo-600 dark:text-indigo-400">{k}</strong>
                            </span>
                          </div>
                          <span className="text-[10px] bg-emerald-50 dark:bg-emerald-950/40 text-emerald-600 dark:text-emerald-400 px-2 py-0.5 rounded font-mono font-semibold border border-emerald-200/50 dark:border-emerald-800/40">
                            Compiled HTML
                          </span>
                        </div>
                        <div className="p-6 bg-white dark:bg-slate-950 min-h-[240px]">
                          <div
                            className="text-slate-900 dark:text-slate-100 text-sm leading-relaxed"
                            dangerouslySetInnerHTML={{ __html: String(v) }}
                          />
                        </div>
                      </div>
                    ))}
                  </div>
                );
              })()}
            </div>
          ) : (
            <div className="flex h-56 flex-col items-center justify-center text-center p-8 text-slate-400 space-y-2">
              <Play className="h-8 w-8 text-slate-300 dark:text-slate-700" />
              <p className="text-xs font-medium">Ready to compile & render</p>
              <p className="text-[11px] max-w-xs text-slate-400">
                Provide test input variables in the JSON editor above, then click <strong>Render Preview</strong> to inspect the Model output.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
